name: Android APK One-Click

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Build debug APK (already signed with debug keystore)
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 8.8
          arguments: assembleDebug

      - name: Rename artifact
        run: |
          mkdir -p out
          cp app/build/outputs/apk/debug/app-debug.apk out/MariaInv-debug.apk

      - name: Create GitHub Release (if tag push)
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: out/MariaInv-debug.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload artifact (manual run)
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        uses: actions/upload-artifact@v4
        with:
          name: MariaInv-debug-apk
          path: out/MariaInv-debug.apk
